openapi: 3.0.3
info:
  title: Swagger EPAM Labs
  contact:
    email: efimchiksasha@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/api/v0
paths:
  /triangle_checker:
    summary: Triangle options
    get:
      summary: Get triangle options by sides
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      parameters:
        - in: query
          name: A
          required: true
          schema:
            type: integer
            default: 20
        - in: query
          name: B
          required: true
          schema:
            type: integer
            default: 20
        - in: query
          name: C
          required: true
          schema:
            type: integer
            default: 20
  /allive:
    summary: Check server helth
    get:
      summary: Response hello message, if server is up
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
